version: "3.9"

services:
  backend:
    build: ./backend
    image: my-backend:1.0
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./app
    image: my-frontend:1.0
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    depends_on:
      - backend
