# Generated by Django 5.2.5 on 2025-08-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0002_remove_image_url_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='clickdrop_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed/'),
        ),
        migrations.AddField(
            model_name='image',
            name='text_removal_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='text_removal_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='text_removed',
            field=models.BooleanField(default=False),
        ),
    ]
