# Generated by Django 5.2.5 on 2025-09-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0003_image_clickdrop_task_id_image_processed_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='compressed_image',
            field=models.ImageField(blank=True, null=True, upload_to='compressed/'),
        ),
        migrations.AddField(
            model_name='image',
            name='compressed_size',
            field=models.IntegerField(blank=True, help_text='Compressed file size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='compression_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='compression_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='compression_ratio',
            field=models.FloatField(blank=True, help_text='Compression ratio (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='compression_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='original_size',
            field=models.IntegerField(blank=True, help_text='Original file size in bytes', null=True),
        ),
    ]
